create table t_igift(
	id varchar(40) primary key,
	name varchar(50) comment '礼品名称',
	type int comment '礼品类型：{1.实物,2.电子券}',
	integral int comment '需要的积分数',
	stocknum int comment '礼品库存数量',
	limitnum int comment '每人限购次数',
	tradenum int comment '已经兑换数量',
	small_image varchar(255) comment '小图',
	big_image varchar(255) comment '大图',
	intro varchar(255) comment '礼品简介',
	notes varchar(255) comment '换购须知',
	start_time datetime comment '开始时间',
	end_time datetime comment '结束时间',
	weight bigint comment '排序',
	create_user varchar(40) comment '创建用户',
	create_time datetime comment '创建时间',
	update_user varchar(40) comment '修改用户',
	update_time datetime comment '修改时间',
	state bool comment '记录状态{true/false}'
) character set utf8 collate utf8_general_ci comment '积分礼品表';

create table t_gifts_order(
	id bigint primary key auto_increment,
	order_no varchar(40) comment '订单编号',
	integral int comment '消耗积分数',
	integral_source_id varchar(2550) comment '积分来源ID',
	user_id varchar(40) comment '换购用户ID',
	username varchar(40) comment '换购用户账号',
	realname varchar(40) comment '换购用户姓名',
	mobile varchar(40) comment '换购用户联系方式',
	gift_id varchar(40) comment '礼品ID',
	giftname varchar(50) comment '礼品名称',
	gifttype int comment '礼品类型',
	images varchar(2550) comment '礼品图片',
	nums int comment '礼品数量',
	note varchar(255) comment '用户备注',
	address varchar(50) comment '收货地址',
	status int comment '状态{0.已取消|1.未发货,2.已发货,3.已收货|1.未使用,2.已使用}',
	create_user varchar(40) comment '创建用户',
	create_time datetime comment '创建时间',
	update_user varchar(40) comment '修改用户',
	update_time datetime comment '修改时间',
	state bool comment '记录状态{true/false}'
) character set utf8 collate utf8_general_ci comment '礼品订单表';